- name: remove the Docker package
  yum:
    name: docker, container-selinux, docker-common
    state: absent

- name: install the latest version of Docker
  yum:
    name: docker
    update_cache: yes
    state: latest

- name: Start the docker service
  service: name=docker state=started enabled=yes


